/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecurityUserDto } from '../../models/security-user-dto';

export interface SecurityUserControllerGetById$Params {

/**
 * Id do Usuario
 */
  id: number;
}

export function securityUserControllerGetById(http: HttpClient, rootUrl: string, params: SecurityUserControllerGetById$Params, context?: HttpContext): Observable<StrictHttpResponse<SecurityUserDto>> {
  const rb = new RequestBuilder(rootUrl, securityUserControllerGetById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SecurityUserDto>;
    })
  );
}

securityUserControllerGetById.PATH = '/api/v1/user/{id}';
