/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SecurityUserControllerGetGroupReport$Params {

/**
 * Código do Grupo
 */
  idGrupo: number;
}

export function securityUserControllerGetGroupReport(http: HttpClient, rootUrl: string, params: SecurityUserControllerGetGroupReport$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, securityUserControllerGetGroupReport.PATH, 'get');
  if (params) {
    rb.path('idGrupo', params.idGrupo, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/pdf', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

securityUserControllerGetGroupReport.PATH = '/api/v1/user/users-report/{idGrupo}';
