/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecurityUserDto } from '../../models/security-user-dto';
import { SecurityUserFilterDto } from '../../models/security-user-filter-dto';

export interface SecurityUserControllerGetUsersByFilter$Params {

/**
 * Filtro de pesquisa
 */
  filtroDTO: SecurityUserFilterDto;
}

export function securityUserControllerGetUsersByFilter(http: HttpClient, rootUrl: string, params: SecurityUserControllerGetUsersByFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SecurityUserDto>>> {
  const rb = new RequestBuilder(rootUrl, securityUserControllerGetUsersByFilter.PATH, 'get');
  if (params) {
    rb.query('filtroDTO', params.filtroDTO, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SecurityUserDto>>;
    })
  );
}

securityUserControllerGetUsersByFilter.PATH = '/api/v1/user/filter';
