/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageTaskDto } from '../../models/page-task-dto';

export interface TaskControllerListAllPage$Params {
  page: Pageable;
}

export function taskControllerListAllPage(http: HttpClient, rootUrl: string, params: TaskControllerListAllPage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageTaskDto>> {
  const rb = new RequestBuilder(rootUrl, taskControllerListAllPage.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageTaskDto>;
    })
  );
}

taskControllerListAllPage.PATH = '/api/v1/task/page';
