/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDto } from '../../models/task-dto';
import { TaskUpdateDto } from '../../models/task-update-dto';

export interface TaskControllerUpdate$Params {
  id: number;
      body: TaskUpdateDto
}

export function taskControllerUpdate(http: HttpClient, rootUrl: string, params: TaskControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDto>> {
  const rb = new RequestBuilder(rootUrl, taskControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDto>;
    })
  );
}

taskControllerUpdate.PATH = '/api/v1/task/{id}';
