/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { SecurityUserApiService } from './services/security-user-api.service';
import { TaskControllerService } from './services/task-controller.service';
import { StudentControllerService } from './services/student-controller.service';
import { PersonControllerService } from './services/person-controller.service';
import { SecurityGroupApiService } from './services/security-group-api.service';
import { StudentCrudControllerService } from './services/student-crud-controller.service';
import { CategoryControllerService } from './services/category-controller.service';
import { AuthApiService } from './services/auth-api.service';
import { ControllerHelloWorldService } from './services/controller-hello-world.service';
import { SecurityModuleApiService } from './services/security-module-api.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    SecurityUserApiService,
    TaskControllerService,
    StudentControllerService,
    PersonControllerService,
    SecurityGroupApiService,
    StudentCrudControllerService,
    CategoryControllerService,
    AuthApiService,
    ControllerHelloWorldService,
    SecurityModuleApiService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
