/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthDto } from './models/auth-dto';
export { AuthUserDto } from './models/auth-user-dto';
export { CategoryDto } from './models/category-dto';
export { CredencialDto } from './models/credencial-dto';
export { FieldResponse } from './models/field-response';
export { GenericDto } from './models/generic-dto';
export { GroupStatisticsDto } from './models/group-statistics-dto';
export { MessageResponse } from './models/message-response';
export { PersonDataDto } from './models/person-data-dto';
export { PersonDto } from './models/person-dto';
export { PersonListDto } from './models/person-list-dto';
export { SecurityFeatureDto } from './models/security-feature-dto';
export { SecurityGroupDto } from './models/security-group-dto';
export { SecurityGroupFeatureDto } from './models/security-group-feature-dto';
export { SecurityGroupFilterDto } from './models/security-group-filter-dto';
export { SecurityModuleDto } from './models/security-module-dto';
export { SecurityUserDto } from './models/security-user-dto';
export { SecurityUserFilterDto } from './models/security-user-filter-dto';
export { SecurityUserFoneDto } from './models/security-user-fone-dto';
export { SecurityUserGroupDto } from './models/security-user-group-dto';
export { Student } from './models/student';
export { StudentCreateDto } from './models/student-create-dto';
export { StudentDto } from './models/student-dto';
export { StudentListDto } from './models/student-list-dto';
export { StudentUpdateDto } from './models/student-update-dto';
export { TaskCreateDto } from './models/task-create-dto';
export { TaskDto } from './models/task-dto';
export { TaskUpdateDto } from './models/task-update-dto';
