/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenericDto {

  /**
   * Método abstrato para retornar o ID do DTO
   */
  id?: number;
}
