/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Entidade de transferência de Estatística de Grupo
 */
export interface GroupStatisticsDto {

  /**
   * Descrição do Grupo
   */
  descricao?: string;

  /**
   * id do Grupo
   */
  id?: number;

  /**
   * Nome do Grupo
   */
  nome?: string;

  /**
   * Total de Usuários do grupo
   */
  totalUsuarios?: number;
}
