/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonDto {
  birthday?: string;
  cpf?: string;
  gender?: string;
  id?: number;
  name?: string;
}
