/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados do filtro de pesquisa de Grupos
 */
export interface SecurityGroupFilterDto {

  /**
   * Grupo ativo
   */
  active?: boolean;

  /**
   * Identificação do Módulo
   */
  moduleId?: number;

  /**
   * Nome do Grupo
   */
  name?: string;
}
