/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Entidade de transferência de Telefone
 */
export interface SecurityUserFoneDto {

  /**
   * DDD do Telefone
   */
  ddd?: string;

  /**
   * Código do Telefone
   */
  id?: string;

  /**
   * Número do Telefone
   */
  number?: string;

  /**
   * Descrição do Tipo do Telefone
   */
  typeDescription?: string;

  /**
   * Código do Tipo do Telefone
   */
  typeId?: number;

  /**
   * Código do Usuário
   */
  userId?: string;
}
