/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Entidade de transferência de Usuario Grupos
 */
export interface SecurityUserGroupDto {

  /**
   * Código do Grupo
   */
  groupId?: string;

  /**
   * Nome do Grupo
   */
  groupName?: string;

  /**
   * Código do Usuário Grupo
   */
  id?: string;

  /**
   * Código do Usuário
   */
  userId?: string;
}
