/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityGroupFeatureDto } from '../models/security-group-feature-dto';

/**
 * Entidade de transferência de Grupo
 */
export interface SecurityGroupDto {

  /**
   * indica se o Grupo de Usuários é de administradores
   */
  administrator?: boolean;

  /**
   * Descricao do Grupo de Usuários
   */
  description?: string;

  /**
   * Lista de Grupo Funcionalidades que o Grupo de usuário possui
   */
  groupFeatures?: Array<SecurityGroupFeatureDto>;

  /**
   * Código do Grupo de Usuários
   */
  id?: number;

  /**
   * Nome do Grupo de usuários
   */
  name?: string;

  /**
   * Código do Status do Grupo de Usuários
   */
  status?: boolean;
}
