/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityFeatureDto } from '../models/security-feature-dto';

/**
 * Entidade de transferência de Modulos do sistema
 */
export interface SecurityModuleDto {

  /**
   * Indica se todos os modulos estão checados, onlyFront
   */
  allChecked?: boolean;

  /**
   * Lista de Funcionalidades do Módulo
   */
  features?: Array<SecurityFeatureDto>;

  /**
   * Código do Modulo do sistema
   */
  id?: string;

  /**
   * Indica se o acordeon está aberto, onlyFront
   */
  isAccordionOpen?: boolean;

  /**
   * Código Mnemonico da Funcionalidade
   */
  mnemonic?: string;

  /**
   * Nome do Modulo do sistema
   */
  name?: string;

  /**
   * Descrição do Status do Usuário
   */
  statusDescription?: string;

  /**
   * Código do Status do Usuário
   */
  statusId?: string;
}
