/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Entidade de transferência de dados de filtro de Usuário
 */
export interface SecurityUserFilterDto {

  /**
   * Usuário Ativo
   */
  active?: boolean;

  /**
   * Login do Usuário
   */
  login?: string;

  /**
   * Nome do Usuário
   */
  name?: string;
}
