/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityUserFoneDto } from '../models/security-user-fone-dto';
import { SecurityUserGroupDto } from '../models/security-user-group-dto';

/**
 * Entidade de transferência de Usuario
 */
export interface SecurityUserDto {

  /**
   * Acesso do Usuário Bloqueado
   */
  blockedAccess?: boolean;

  /**
   * Data do cadastro do Usuário
   */
  createdDate?: string;

  /**
   * Email do usuário
   */
  email?: string;

  /**
   * Telefones do Usuário
   */
  fones?: Array<SecurityUserFoneDto>;

  /**
   * Grupos do Usuário
   */
  groups?: Array<SecurityUserGroupDto>;

  /**
   * Código do Usuário
   */
  id?: string;

  /**
   * Data da última atualização do cadastro do Usuário
   */
  lastUpdateDate?: string;

  /**
   * Login do Usuário
   */
  login?: string;

  /**
   * Nome do Usuário
   */
  name?: string;

  /**
   * Código do Status do Usuário
   */
  status?: boolean;
}
