/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityFeatureDto } from '../models/security-feature-dto';

/**
 * Entidade de transferência de Grupo funcionalidades
 */
export interface SecurityGroupFeatureDto {
  feature?: SecurityFeatureDto;

  /**
   * Código do Grupo
   */
  groupId?: string;

  /**
   * Código do Grupo Funcionalidade
   */
  id?: string;
}
