/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Entidade de transferência de Funcionalidade
 */
export interface SecurityFeatureDto {

  /**
   * Indica se a funcionalidade está marcada, OnlyFront
   */
  checked?: boolean;

  /**
   * Código da Funcionalidade
   */
  id?: string;

  /**
   * Código Mnemonico da Funcionalidade
   */
  mnemonic?: string;

  /**
   * Nome da Funcionalidade
   */
  name?: string;

  /**
   * Descrição do Status do Usuário
   */
  statusDescription?: string;

  /**
   * Código do Status do Usuário
   */
  statusId?: string;
}
