/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentDto {
  course?: string;
  createdDate?: string;
  id?: number;
  name?: string;
  registerNumber?: string;
}
