/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentCreateDto {

  /**
   * Nome do Curso
   */
  courseRegister?: string;

  /**
   * Nome do aluno
   */
  name: string;

  /**
   * Número de matricula
   */
  registerNumber?: string;
}
