/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenericDto } from '../models/generic-dto';

/**
 * DTO para tarefas
 */
export type TaskDto = GenericDto & {

/**
 * ID da tarefa
 */
'id'?: number;

/**
 * Descrição da tarefa
 */
'description'?: string;

/**
 * Tarefa concluída
 */
'completed'?: boolean;

/**
 * ID da Categoria da tarefa
 */
'category_id'?: number;

/**
 * Nome da Categoria da tarefa
 */
'category_name'?: string;

/**
 * Data quando limite para execução da tarefa
 */
'dueDate'?: string;
} & {
};
