/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskDto {
  category_id?: number;
  category_name?: string;
  completed?: boolean;
  description?: string;
  dueDate?: string;
  id?: number;
}
