/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskCreateDto {

  /**
   * ID da Categoria da tarefa
   */
  category_id?: number;

  /**
   * Descrição da tarefa
   */
  description: string;

  /**
   * Data quando limite para execução da tarefa
   */
  dueDate?: string;
}
