/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/student-controller/create';
import { Create$Params } from '../fn/student-controller/create';
import { getById } from '../fn/student-controller/get-by-id';
import { GetById$Params } from '../fn/student-controller/get-by-id';
import { listAll } from '../fn/student-controller/list-all';
import { ListAll$Params } from '../fn/student-controller/list-all';
import { listYesterdayRegisters } from '../fn/student-controller/list-yesterday-registers';
import { ListYesterdayRegisters$Params } from '../fn/student-controller/list-yesterday-registers';
import { remove } from '../fn/student-controller/remove';
import { Remove$Params } from '../fn/student-controller/remove';
import { Student } from '../models/student';
import { update } from '../fn/student-controller/update';
import { Update$Params } from '../fn/student-controller/update';

@Injectable({ providedIn: 'root' })
export class StudentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/api/v1/student/{id}';

  /**
   * End point para obter dados de aluno
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para obter dados de aluno
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<{
}> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/api/v1/student/{id}';

  /**
   * End point para inclusão de aluno
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para inclusão de aluno
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<{
}> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `remove()` */
  static readonly RemovePath = '/api/v1/student/{id}';

  /**
   * End point para remover dados de aluno
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `remove()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove$Response(params: Remove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return remove(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para remover dados de aluno
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `remove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove(params: Remove$Params, context?: HttpContext): Observable<{
}> {
    return this.remove$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `listAll()` */
  static readonly ListAllPath = '/api/v1/student';

  /**
   * lista todos os estudantes
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll$Response(params?: ListAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Student>>> {
    return listAll(this.http, this.rootUrl, params, context);
  }

  /**
   * lista todos os estudantes
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll(params?: ListAll$Params, context?: HttpContext): Observable<Array<Student>> {
    return this.listAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Student>>): Array<Student> => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/api/v1/student';

  /**
   * End point para inclusão de aluno
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para inclusão de aluno
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<{
}> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `listYesterdayRegisters()` */
  static readonly ListYesterdayRegistersPath = '/api/v1/student/yesterday-registers';

  /**
   * lista todos os estudantes matriculados antes de hoje
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listYesterdayRegisters()` instead.
   *
   * This method doesn't expect any request body.
   */
  listYesterdayRegisters$Response(params?: ListYesterdayRegisters$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Student>>> {
    return listYesterdayRegisters(this.http, this.rootUrl, params, context);
  }

  /**
   * lista todos os estudantes matriculados antes de hoje
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listYesterdayRegisters$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listYesterdayRegisters(params?: ListYesterdayRegisters$Params, context?: HttpContext): Observable<Array<Student>> {
    return this.listYesterdayRegisters$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Student>>): Array<Student> => r.body)
    );
  }

}
