/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentDto } from '../../models/student-dto';
import { StudentUpdateDto } from '../../models/student-update-dto';

export interface StudentCrudControllerUpdate$Params {
  id: number;
      body: StudentUpdateDto
}

export function studentCrudControllerUpdate(http: HttpClient, rootUrl: string, params: StudentCrudControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentDto>> {
  const rb = new RequestBuilder(rootUrl, studentCrudControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentDto>;
    })
  );
}

studentCrudControllerUpdate.PATH = '/api/v1/crud-student/{id}';
