/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchFieldValue } from '../../models/search-field-value';
import { StudentListDto } from '../../models/student-list-dto';

export interface StudentCrudControllerSearchFieldsAction$Params {
      body: Array<SearchFieldValue>
}

export function studentCrudControllerSearchFieldsAction(http: HttpClient, rootUrl: string, params: StudentCrudControllerSearchFieldsAction$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentListDto>>> {
  const rb = new RequestBuilder(rootUrl, studentCrudControllerSearchFieldsAction.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StudentListDto>>;
    })
  );
}

studentCrudControllerSearchFieldsAction.PATH = '/api/v1/crud-student/search-fields';
