/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageStudentListDto } from '../../models/page-student-list-dto';

export interface StudentCrudControllerListAllPage$Params {
  page: Pageable;
}

export function studentCrudControllerListAllPage(http: HttpClient, rootUrl: string, params: StudentCrudControllerListAllPage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStudentListDto>> {
  const rb = new RequestBuilder(rootUrl, studentCrudControllerListAllPage.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageStudentListDto>;
    })
  );
}

studentCrudControllerListAllPage.PATH = '/api/v1/crud-student/page';
