/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentCreateDto } from '../../models/student-create-dto';
import { StudentDto } from '../../models/student-dto';

export interface StudentCrudControllerCreate$Params {
      body: StudentCreateDto
}

export function studentCrudControllerCreate(http: HttpClient, rootUrl: string, params: StudentCrudControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentDto>> {
  const rb = new RequestBuilder(rootUrl, studentCrudControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentDto>;
    })
  );
}

studentCrudControllerCreate.PATH = '/api/v1/crud-student';
