/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupStatisticsDto } from '../../models/group-statistics-dto';

export interface SecurityGroupControllerGetGroupStatistics$Params {
}

export function securityGroupControllerGetGroupStatistics(http: HttpClient, rootUrl: string, params?: SecurityGroupControllerGetGroupStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupStatisticsDto>>> {
  const rb = new RequestBuilder(rootUrl, securityGroupControllerGetGroupStatistics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GroupStatisticsDto>>;
    })
  );
}

securityGroupControllerGetGroupStatistics.PATH = '/api/v1/groups/statistics';
