/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecurityGroupDto } from '../../models/security-group-dto';

export interface SecurityGroupControllerUpdate$Params {
  id: number;
      body: SecurityGroupDto
}

export function securityGroupControllerUpdate(http: HttpClient, rootUrl: string, params: SecurityGroupControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SecurityGroupDto>> {
  const rb = new RequestBuilder(rootUrl, securityGroupControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SecurityGroupDto>;
    })
  );
}

securityGroupControllerUpdate.PATH = '/api/v1/groups/{id}';
