/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecurityModuleDto } from '../../models/security-module-dto';

export interface GetActiveModules$Params {
}

export function getActiveModules(http: HttpClient, rootUrl: string, params?: GetActiveModules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SecurityModuleDto>>> {
  const rb = new RequestBuilder(rootUrl, getActiveModules.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SecurityModuleDto>>;
    })
  );
}

getActiveModules.PATH = '/api/v1/modules/active-modules';
