/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecurityGroupDto } from '../../models/security-group-dto';
import { SecurityGroupFilterDto } from '../../models/security-group-filter-dto';

export interface GetAllGroupByFilter$Params {

/**
 * Filtro de pesquisa
 */
  securityGroupFilterDTO: SecurityGroupFilterDto;
}

export function getAllGroupByFilter(http: HttpClient, rootUrl: string, params: GetAllGroupByFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SecurityGroupDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllGroupByFilter.PATH, 'get');
  if (params) {
    rb.query('securityGroupFilterDTO', params.securityGroupFilterDTO, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SecurityGroupDto>>;
    })
  );
}

getAllGroupByFilter.PATH = '/api/v1/groups/filter';
